// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class ActiveCondition: BaseModel
  {
    public Character character;
    public Condition condition;
    public int cooldownRemaining;
    public CreatureInstance creature;
    public int damage;
    public int roundsRemaining;
    public CreatureInstance target;
  }
}