// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Action: BaseModel
  {
    public string description;
    public int initiative;
    public string name;
    public string spellDmgRange;
    public int value;
  }
}