// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class ArmorInstance: BaseModel
  {
    public ArmorClass armorClass;
    public ArmorInstanceAttribute[] attributes;
    public bool damaged;
    public bool equipped;
    public Inventory inventory;
    public ArmorLocation location;
    public ArmorInstanceDamageReduction[] reductions;
  }
}