// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class ArmorInstanceDamageReduction: BaseModel
  {
    public ArmorInstance armor;
    public DamageType damageType;
    public string name;
    public int value;
  }
}