// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class ArmorInstance
  {
    public ArmorClass armorClass;
    public ArmorInstanceAttribute[] attributes;
    public bool damaged;
    public bool equipped;
    public Inventory inventory;
    public ArmorLocation location;
    public ArmorInstanceDamageReduction[] reductions;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}