// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class ArmorLocation: BaseModel
  {
    public EquipLocation location;
    public string name;
  }
}