// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class ArmorInstanceDamageReduction
  {
    public ArmorInstance armor;
    public DamageType damageType;
    public string name;
    public int value;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}