// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class ArmorClass: BaseModel
  {
    public int durability;
    public string name;
    public ClassDamageReduction[] reductions;
  }
}