// Autogenerated 2/8/2022 1:58:55 PM
using System;

namespace Openworld.Models
{
	[Serializable]
	public class BaseModel
	{
    public string id;
    public string createdAt;
    public string updatedAt;

		public override string ToString(){
			return UnityEngine.JsonUtility.ToJson (this, true);
		}
	}
}