// Autogenerated 2/25/2022 11:17:41 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  [Serializable]
  public class BattleResponse
  {
    public string displayName;
    public string id;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}