// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class BattleDamageRequest : ObservableObject
  {
    private int[] _characters;
    public int[] characters {
      get => _characters;
      set => Set(ref _characters, value);
    }

    private int[] _creatures;
    public int[] creatures {
      get => _creatures;
      set => Set(ref _creatures, value);
    }

    private int _damageAmt;
    public int damageAmt {
      get => _damageAmt;
      set => Set(ref _damageAmt, value);
    }

    private int _damageType;
    public int damageType {
      get => _damageType;
      set => Set(ref _damageType, value);
    }
  }
}