// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class BattleResponse : ObservableObject
  {
    private string _displayName;
    public string displayName {
      get => _displayName;
      set => Set(ref _displayName, value);
    }

    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}