// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class BattleDamageRequest : ObservableObject
  {
    private int[] _characters;
    public int[] characters {
      get => _characters;
      set => Set(ref _characters, value);
    }

    private int[] _creatures;
    public int[] creatures {
      get => _creatures;
      set => Set(ref _creatures, value);
    }

    private int _damageAmt;
    public int damageAmt {
      get => _damageAmt;
      set => Set(ref _damageAmt, value);
    }

    private int _damageType;
    public int damageType {
      get => _damageType;
      set => Set(ref _damageType, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}