// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class BattleResponse : ObservableObject
  {
    private string _displayName;
    public string displayName {
      get => _displayName;
      set => Set(ref _displayName, value);
    }

    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }
  }
}