// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class BattleDamageRequest
  {
    public int[] characters;
    public int[] creatures;
    public int damageAmt;
    public int damageType;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}