// Autogenerated 2/15/2022 10:30:15 AM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Battle
  {
    public string id;
    public string createdAt;
    // public CreatureInstance[] enemies;
    // public CreatureInstance[] friendlies;
    // public Game game;
    // public Character initiator;
    // public Character[] participants;
    public int round;

    public string getName(){
      //convert createdAt to DateTime, then format to string
      DateTime createdAt = DateTime.Parse(this.createdAt);
      return createdAt.ToString("yyyy/MM/dd HH:mm:ss");
    }

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}