// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class Battle : ObservableObject
  {
    private string _displayName;
    public string displayName {
      get => _displayName;
      set => Set(ref _displayName, value);
    }

    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }
  }
}