// Autogenerated 4/8/2022 6:02:31 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld;

namespace Openworld.Models
{
  [Serializable]
  public class CharacterDetail : PublicCharacter
  {
    public int castSpeed;
    public int defChance;
    public int dexterity;
    public int healSpeed;
    public int hitChance;
    public int hp;
    public int intelligence;
    public Inventory inventory;
    public int inventorySize;
    public int mana;
    public int movement;
    public int parry;
    public string player;
    public int resistC;
    public int resistE;
    public int resistF;
    public int resistP;
    public int resistPh;
    public CharacterSkill[] skills;
    public int stamina;
    public int strength;
    public int swingSpeed;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}