// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class CharacterSkill : ObservableObject
  {
    private string _description;
    public string description {
      get => _description;
      set => Set(ref _description, value);
    }

    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }

    private int _level;
    public int level {
      get => _level;
      set => Set(ref _level, value);
    }

    private string _name;
    public string name {
      get => _name;
      set => Set(ref _name, value);
    }
  }
}