// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Character: BaseModel
  {
    public int baseDmgIncrease;
    public int baseResist;
    public Battle[] battles;
    public ActiveCondition[] conditions;
    public int deC;
    public int deE;
    public int deF;
    public int deP;
    public int dePh;
    public int dmgIncrease;
    public Game game;
    public int hp;
    public Inventory inventory;
    public int maxHp;
    public string name;
    public CreatureInstance[] pets;
    public User player;
    public int resistC;
    public int resistE;
    public int resistF;
    public int resistP;
    public int resistPh;
    public int spellDmgIncrease;
  }
}