// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class ClassDamageReduction: BaseModel
  {
    public ArmorClass armorClass;
    public DamageType damageType;
    public int level;
    public string reduction;
  }
}