// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class ClassDamageReduction
  {
    public ArmorClass armorClass;
    public DamageType damageType;
    public int level;
    public string reduction;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}