// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class Condition
  {
    public string actionReplace;
    public bool allowMultiple;
    public int cooldown;
    public string damage;
    public DamageType damageType;
    public int delay;
    public int duration;
    public string name;
    public Condition[] overrides;
    public bool removeOnHit;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}