// Autogenerated 4/8/2022 6:02:31 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  [Serializable]
  public class CreateCharacterSkillRequest
  {
    public string skillId;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}