// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class CreatureInstance
  {
    public DamageType actionDamageType;
    public string actionDescription;
    public int actionDmgAmount;
    public string actionName;
    public int actionValue;
    public int anatomy;
    public bool animate;
    public int appetite;
    public string baseDmg;
    public Battle battleAsEnemy;
    public Battle battleAsFriendly;
    public ActiveCondition[] conditions;
    public int counter;
    public int dexterity;
    public int evalInt;
    public string hoverStats;
    public int hp;
    public int initiative;
    public int intelligence;
    public Inventory loot;
    public int magery;
    public int meleeDmg;
    public Monster monster;
    public string name;
    public MonsterAction nextAction;
    public int obedience;
    public int orighp;
    public Character owner;
    public int resistC;
    public int resistE;
    public int resistF;
    public int resistP;
    public int resistPh;
    public int resistSpell;
    public string specials;
    public int stomach;
    public int strength;
    public int tactics;
    public string tameName;
    public bool tamed;
    public int tracking;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}