// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class CreateCharacterRequest : ObservableObject
  {
    private string _name;
    public string name
    {
      get => _name;
      set => Set(ref _name, value);
    }

    private int _strength;
    public int strength
    {
      get => _strength;
      set => Set(ref _strength, value);
    }

    private int _dexterity;
    public int dexterity
    {
      get => _dexterity;
      set => Set(ref _dexterity, value);
    }

    private int _intelligence;
    public int intelligence
    {
      get => _intelligence;
      set => Set(ref _intelligence, value);
    }

    private int _raceId;
    public int raceId
    {
      get => _raceId;
      set => Set(ref _raceId, value);
    }

    private CharacterSkill[] _skills;
    public CharacterSkill[] skills
    {
      get => _skills;
      set => Set(ref _skills, value);
    }
  }
}