// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class CreateCharacterRequest : ObservableObject
  {
    private string _name;
    public string name
    {
      get => _name;
      set => Set(ref _name, value);
    }

    private int _race;
    public int race
    {
      get => _race;
      set => Set(ref _race, value);
    }

    private Skill[] _skills;
    public Skill[] skills
    {
      get => _skills;
      set => Set(ref _skills, value);
    }
  }
}