// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class CreateCharacterSkillRequest : ObservableObject
  {
    private string _skillId;
    public string skillId {
      get => _skillId;
      set => Set(ref _skillId, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}