// Autogenerated 2/15/2022 10:10:59 AM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class CreateCharacterRequest
  {
    public int baseResist;
    public int inventorySize;
    public int maxHp;
    public string name;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}