// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class DamageType: BaseModel
  {
    public bool chaos;
    public string description;
    public bool display;
    public string imgurl;
    public string name;
    public string soundurl;
  }
}