// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class DamageResponse
  {
    public string result;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}