// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class DamageType
  {
    public bool chaos;
    public string description;
    public bool display;
    public string imgurl;
    public string name;
    public string soundurl;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}