// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class Error : ObservableObject
  {
    private string _message;
    public string message {
      get => _message;
      set => Set(ref _message, value);
    }

    private string _type;
    public string type {
      get => _type;
      set => Set(ref _type, value);
    }
  }
}