// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class Error : ObservableObject
  {
    private string _message;
    public string message {
      get => _message;
      set => Set(ref _message, value);
    }

    private string _type;
    public string type {
      get => _type;
      set => Set(ref _type, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}