// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class Error : ObservableObject
  {
    private string _message;
    public string message {
      get => _message;
      set => Set(ref _message, value);
    }

    private string _type;
    public string type {
      get => _type;
      set => Set(ref _type, value);
    }
  }
}