// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class FailResponse : ObservableObject
  {
    private Error _error;
    public Error error {
      get => _error;
      set => Set(ref _error, value);
    }

    private bool _success;
    public bool success {
      get => _success;
      set => Set(ref _success, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}