// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class FailResponse : ObservableObject
  {
    private Error _error;
    public Error error {
      get => _error;
      set => Set(ref _error, value);
    }

    private bool _success;
    public bool success {
      get => _success;
      set => Set(ref _success, value);
    }
  }
}