// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class FailResponse : ObservableObject
  {
    private Error _error;
    public Error error {
      get => _error;
      set => Set(ref _error, value);
    }

    private bool _success;
    public bool success {
      get => _success;
      set => Set(ref _success, value);
    }
  }
}