// Autogenerated 2/15/2022 10:10:59 AM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Game
  {
    //public Battle[] battles;
    //public Character[] characters;
    public string id;
    public int maxPlayers;
    public string name;
    //public User owner;
    //public User[] players;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}