// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class GameCharacter: BaseModel
  {
    public Character character;
    public Game game;
    public bool owner;
  }
}