// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Game: BaseModel
  {
    public Battle[] battles;
    public Character[] characters;
    public int maxPlayers;
    public string name;
    public User owner;
    public User[] players;
  }
}