// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class GameResponse : Game
  {
    private string[] _battles;
    public string[] battles {
      get => _battles;
      set => Set(ref _battles, value);
    }

    private string[] _characters;
    public string[] characters {
      get => _characters;
      set => Set(ref _characters, value);
    }

    private string[] _players;
    public string[] players {
      get => _players;
      set => Set(ref _players, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}