// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class GameResponse : Game
  {
    private string[] _battles;
    public string[] battles {
      get => _battles;
      set => Set(ref _battles, value);
    }

    private string[] _characters;
    public string[] characters {
      get => _characters;
      set => Set(ref _characters, value);
    }

    private string[] _players;
    public string[] players {
      get => _players;
      set => Set(ref _players, value);
    }
  }
}