// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Gem: BaseModel
  {
    public ItemCategory category;
    public string image;
    public int level;
    public string name;
    public GemRarity rarity;
    public int weight;
  }
}