// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class Inventory
  {
    public ArmorInstance[] armor;
    public int capacity;
    public int gold;
    public JewelryInstance[] jewelry;
    public bool limit;
    public SpellbookInstance[] spellbooks;
    public WeaponInstance[] weapons;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}