// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Inventory: BaseModel
  {
    public ArmorInstance[] armor;
    public int capacity;
    public int gold;
    public JewelryInstance[] jewelry;
    public bool limit;
    public SpellbookInstance[] spellbooks;
    public WeaponInstance[] weapons;
  }
}