// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class Inventory : ObservableObject
  {
    private string[] _armor;
    public string[] armor {
      get => _armor;
      set => Set(ref _armor, value);
    }

    private int _capacity;
    public int capacity {
      get => _capacity;
      set => Set(ref _capacity, value);
    }

    private int _gold;
    public int gold {
      get => _gold;
      set => Set(ref _gold, value);
    }

    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }

    private string[] _jewelry;
    public string[] jewelry {
      get => _jewelry;
      set => Set(ref _jewelry, value);
    }

    private string[] _spellbooks;
    public string[] spellbooks {
      get => _spellbooks;
      set => Set(ref _spellbooks, value);
    }

    private string[] _weapons;
    public string[] weapons {
      get => _weapons;
      set => Set(ref _weapons, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}