// Autogenerated 2/15/2022 10:10:59 AM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class InvitePlayerRequest
  {
    public string email;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}