// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class ItemDamageResponse : ObservableObject
  {
    private ItemDamageType _result;
    public ItemDamageType result {
      get => _result;
      set => Set(ref _result, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}