// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
namespace Openworld.Models
{
  public enum ItemType
  {
    armor = 1,
    jewelry = 2,
    spellbook = 3,
    weapon = 0
  }
}