// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
namespace Openworld.Models
{
  public enum ItemType
  {
    armor = 1,
    jewelry = 2,
    spellbook = 3,
    weapon = 0
  }
}