// Autogenerated 2/25/2022 10:41:46 PM
//   by GenerateClientEntities. DO NOT MODIFY
namespace Openworld.Models
{
  public enum ItemType
  {
    weapon = 0,
    armor = 1,
    jewelry = 2,
    spellbook = 3
  }
}