// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class JewelryInstance: BaseModel
  {
    public JewelryInstanceAttribute[] attributes;
    public bool damaged;
    public bool equipped;
    public Gem gem;
    public Inventory inventory;
    public JewelryLocation location;
  }
}