// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class JewelryInstanceAttribute
  {
    public JewelryAttribute attribute;
    public JewelryInstance jewelry;
    public Skill skill;
    public int value;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}