// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class JewelryInstanceAttribute: BaseModel
  {
    public JewelryAttribute attribute;
    public JewelryInstance jewelry;
    public Skill skill;
    public int value;
  }
}