// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class LoginResponse : ObservableObject
  {
    private string _player;
    public string player {
      get => _player;
      set => Set(ref _player, value);
    }

    private string _token;
    public string token {
      get => _token;
      set => Set(ref _token, value);
    }
  }
}