// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class LoginResponse : ObservableObject
  {
    private string _player;
    public string player {
      get => _player;
      set => Set(ref _player, value);
    }

    private string _token;
    public string token {
      get => _token;
      set => Set(ref _token, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}