// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class Material
  {
    public MaterialType baseMaterial;
    public bool canSpawn;
    public string name;
    public int weaponDurability;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}