// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Material: BaseModel
  {
    public MaterialType baseMaterial;
    public bool canSpawn;
    public string name;
    public int weaponDurability;
  }
}