// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class MonsterClue
  {
    public string clue;
    public Monster monster;
    public int trackingLevel;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}