// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class MonsterRequest : ObservableObject
  {
    private int _monsterId;
    public int monsterId {
      get => _monsterId;
      set => Set(ref _monsterId, value);
    }
  }
}