// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class MonsterAction: BaseModel
  {
    public Action action;
    public string description;
    public Monster monster;
    public int value;
    public int weight;
  }
}