// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class MonsterRequest : ObservableObject
  {
    private int _monsterId;
    public int monsterId {
      get => _monsterId;
      set => Set(ref _monsterId, value);
    }
  }
}