// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class MonsterLoot
  {
    public ItemCategory category;
    public int chance;
    public int level;
    public Monster monster;
    public int qty;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}