// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class MonsterLoot: BaseModel
  {
    public ItemCategory category;
    public int chance;
    public int level;
    public Monster monster;
    public int qty;
  }
}