// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class MonsterAction
  {
    public Action action;
    public string description;
    public Monster monster;
    public int value;
    public int weight;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}