// Autogenerated 2/19/2022 5:42:23 PM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class PlayerDetail : PublicPlayer
  {
    public string email;
    public string id;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}