// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class PublicPlayer : ObservableObject
  {
    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }

    private DateTime _lastSeenAt;
    public DateTime lastSeenAt {
      get => _lastSeenAt;
      set => Set(ref _lastSeenAt, value);
    }

    private string _name;
    public string name {
      get => _name;
      set => Set(ref _name, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}