// Autogenerated 2/15/2022 10:10:59 AM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class RegisterRequest
  {
    public string email;
    public string name;
    public string password;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}