// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class RenamePetRequest : ObservableObject
  {
    private string _name;
    public string name {
      get => _name;
      set => Set(ref _name, value);
    }
  }
}