// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class Skill : ObservableObject
  {
    private string _description;
    public string description {
      get => _description;
      set => Set(ref _description, value);
    }

    private string _id;
    public string id {
      get => _id;
      set => Set(ref _id, value);
    }

    private string _name;
    public string name {
      get => _name;
      set => Set(ref _name, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}