// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class SpellbookInstanceAttribute: BaseModel
  {
    public SpellbookAttribute attribute;
    public Skill skill;
    public SlayerType slayer;
    public SpellbookInstance spellbook;
    public int value;
  }
}