// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class SpellbookInstance
  {
    public SpellbookInstanceAttribute[] attributes;
    public Inventory inventory;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}