// Autogenerated 5/12/2022 7:01:03 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;
using Openworld.Binding;

namespace Openworld.Models
{
  public class UpdateGameRequest : ObservableObject
  {
    private int _maxPlayers;
    public int maxPlayers {
      get => _maxPlayers;
      set => Set(ref _maxPlayers, value);
    }

    private string _name;
    public string name {
      get => _name;
      set => Set(ref _name, value);
    }
  }
}