// Autogenerated 5/10/2022 2:34:36 PM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class UpdateGameRequest : ObservableObject
  {
    private int _maxPlayers;
    public int maxPlayers {
      get => _maxPlayers;
      set => Set(ref _maxPlayers, value);
    }

    private string _name;
    public string name {
      get => _name;
      set => Set(ref _name, value);
    }


    public override string ToString(){
      return Newtonsoft.Json.JsonConvert.SerializeObject(this);
    } 
  }
}