// Autogenerated 5/11/2022 9:44:27 AM
//   by GenerateClientEntities. DO NOT MODIFY
using System;

namespace Openworld.Models
{
  public class UpdateCharacterSkillRequest : ObservableObject
  {
    private int _level;
    public int level {
      get => _level;
      set => Set(ref _level, value);
    }
  }
}