// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class User: BaseModel
  {
    public Character[] characters;
    public Game currentGame;
    public string email;
    public Game[] games;
    public bool isAdmin;
    public DateTime lastSeenAt;
    public string name;
    public string password;
  }
}