// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class WeaponAttribute: BaseModel
  {
    public int hand;
    public string name;
    public WeaponSkill skill;
    public string value;
  }
}