// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class WeaponInstanceAttribute: BaseModel
  {
    public WeaponAttribute attribute;
    public SlayerType slayer;
    public int value;
    public WeaponInstance weapon;
  }
}