// Autogenerated 2/16/2022 10:48:30 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class Weapon
  {
    public string damage;
    public int hand;
    public MaterialType material;
    public string name;
    public SpecialMove primaryMove;
    public int range;
    public SpecialMove secondaryMove;
    public WeaponSkill skill;
    public int speed;
    public int strength;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}