// Autogenerated 2/15/2022 10:30:15 AM
using System;

namespace Openworld.Models
{
  [Serializable]
  public class WeaponInstance
  {
    public WeaponInstanceAttribute[] attributes;
    public bool damaged;
    public bool equipped;
    public Inventory inventory;
    public Material material;
    public Weapon weapon;

    public override string ToString(){
      return UnityEngine.JsonUtility.ToJson (this, true);
    } 
  }
}