// Autogenerated 2/8/2022 1:58:55 PM
using System;


namespace Openworld.Models
{
  [Serializable]
  public class Weapon: BaseModel
  {
    public string damage;
    public int hand;
    public MaterialType material;
    public string name;
    public SpecialMove primaryMove;
    public int range;
    public SpecialMove secondaryMove;
    public WeaponSkill skill;
    public int speed;
    public int strength;
  }
}